### ISSUE TITLE
BDJuno crashes when an invalid prefix arrives

### ISSUE THREAD

**Issue by sebastian-xlabs** [forbole/bdjuno#699]
## Bug description
I'm trying to run bdjuno for Wormhole Testnet, following the steps in the documentation and using the mainnet branch because it is the only one for wormhole. The thing is when I activate the `messages` module, sometimes I got `panic: invalid Bech32 prefix; expected cosmos, got wormhole` and the service restarts. Currently I'm running bdjuno as an ECS Fargate service and the task restarts a lot due this.

```
bdjuno[4453]: panic: invalid Bech32 prefix; expected cosmos, got wormhole
bdjuno[4453]: goroutine 418 [running]:
bdjuno[4453]: github.com/cosmos/ibc-go/v4/modules/core/02-client/types.MsgUpdateClient.GetSigners(...)
bdjuno[4453]:         /home/ubuntu/go/pkg/mod/github.com/cosmos/ibc-go/v4@v4.2.2/modules/core/02-client/types/msgs.go:142
bdjuno[4453]: github.com/forbole/juno/v4/modules/messages.DefaultMessagesParser({0x251a1f8?, 0xc0001f3810?}, {0x250a860, 0xc003bfe630})
bdjuno[4453]:         /home/ubuntu/go/pkg/mod/github.com/forbole/juno/v4@v4.1.1-0.20230221021913-841842bdefed/modules/messages/account_parser.go:64 +0x2b
bdjuno[4453]: github.com/forbole/juno/v4/modules/messages.JoinMessageParsers.func1({0x251a1f8, 0xc0001f3810}, {0x250a860, 0xc003bfe630})
bdjuno[4453]:         /home/ubuntu/go/pkg/mod/github.com/forbole/juno/v4@v4.1.1-0.20230221021913-841842bdefed/modules/messages/account_parser.go:36 +0x7f
bdjuno[4453]: github.com/forbole/juno/v4/modules/messages.JoinMessageParsers.func1({0x251a1f8, 0xc0001f3810}, {0x250a860, 0xc003bfe630})
bdjuno[4453]:         /home/ubuntu/go/pkg/mod/github.com/forbole/juno/v4@v4.1.1-0.20230221021913-841842bdefed/modules/messages/account_parser.go:36 +0x7f
bdjuno[4453]: github.com/forbole/bdjuno/v4/modules.UniqueAddressesParser.func1({0x251a1f8?, 0xc0001f3810?}, {0x250a860?, 0xc003bfe630?})
bdjuno[4453]:         /home/ubuntu/bdjuno/modules/registrar.go:41 +0x52
bdjuno[4453]: github.com/forbole/juno/v4/modules/messages.HandleMsg(0x0, {0x250a860?, 0xc003bfe630}, 0xc002356490, 0x40fedd?, {0x251a1f8, 0xc0001f3810}, {0x2515690, 0xc000132790})
bdjuno[4453]:         /home/ubuntu/go/pkg/mod/github.com/forbole/juno/v4@v4.1.1-0.20230221021913-841842bdefed/modules/messages/message_handler.go:19 +0x89
bdjuno[4453]: github.com/forbole/juno/v4/modules/messages.(*Module).HandleMsg(0xc0036eda10?, 0x24ed000?, {0x250a860?, 0xc003bfe630?}, 0x18cfae0?)
bdjuno[4453]:         /home/ubuntu/go/pkg/mod/github.com/forbole/juno/v4@v4.1.1-0.20230221021913-841842bdefed/modules/messages/module.go:37 +0x45
bdjuno[4453]: github.com/forbole/juno/v4/parser.Worker.handleMessage({0xdb, 0xc000efe8c0, {0x251a1f8, 0xc0001f3810}, {0xc00015c200, 0xd, 0x10}, {0x2516c40, 0xc00130b8c0}, {0x2515690, ...}, ...}, ...)
bdjuno[4453]:         /home/ubuntu/go/pkg/mod/github.com/forbole/juno/v4@v4.1.1-0.20230221021913-841842bdefed/parser/worker.go:299 +0x3fa
bdjuno[4453]: github.com/forbole/juno/v4/parser.Worker.ExportTxs({0xdb, 0xc000efe8c0, {0x251a1f8, 0xc0001f3810}, {0xc00015c200, 0xd, 0x10}, {0x2516c40, 0xc00130b8c0}, {0x2515690, ...}, ...}, ...)
bdjuno[4453]:         /home/ubuntu/go/pkg/mod/github.com/forbole/juno/v4@v4.1.1-0.20230221021913-841842bdefed/parser/worker.go:354 +0x44a
bdjuno[4453]: github.com/forbole/juno/v4/parser.Worker.ExportBlock({0xdb, 0xc000efe8c0, {0x251a1f8, 0xc0001f3810}, {0xc00015c200, 0xd, 0x10}, {0x2516c40, 0xc00130b8c0}, {0x2515690, ...}, ...}, ...)
bdjuno[4453]:         /home/ubuntu/go/pkg/mod/github.com/forbole/juno/v4@v4.1.1-0.20230221021913-841842bdefed/parser/worker.go:233 +0x430
bdjuno[4453]: github.com/forbole/juno/v4/parser.Worker.Process({0xdb, 0xc000efe8c0, {0x251a1f8, 0xc0001f3810}, {0xc00015c200, 0xd, 0x10}, {0x2516c40, 0xc00130b8c0}, {0x2515690, ...}, ...}, ...)
bdjuno[4453]:         /home/ubuntu/go/pkg/mod/github.com/forbole/juno/v4@v4.1.1-0.20230221021913-841842bdefed/parser/worker.go:133 +0x425
bdjuno[4453]: github.com/forbole/juno/v4/parser.Worker.ProcessIfNotExists({0xdb, 0xc000efe8c0, {0x251a1f8, 0xc0001f3810}, {0xc00015c200, 0xd, 0x10}, {0x2516c40, 0xc00130b8c0}, {0x2515690, ...}, ...}, ...)
bdjuno[4453]:         /home/ubuntu/go/pkg/mod/github.com/forbole/juno/v4@v4.1.1-0.20230221021913-841842bdefed/parser/worker.go:94 +0x17d
bdjuno[4453]: github.com/forbole/juno/v4/parser.Worker.Start({0xdb, 0xc000efe8c0, {0x251a1f8, 0xc0001f3810}, {0xc00015c200, 0xd, 0x10}, {0x2516c40, 0xc00130b8c0}, {0x2515690, ...}, ...})
bdjuno[4453]:         /home/ubuntu/go/pkg/mod/github.com/forbole/juno/v4@v4.1.1-0.20230221021913-841842bdefed/parser/worker.go:65 +0x1db
bdjuno[4453]: created by github.com/forbole/juno/v4/cmd/start.startParsing
bdjuno[4453]:         /home/ubuntu/go/pkg/mod/github.com/forbole/juno/v4@v4.1.1-0.20230221021913-841842bdefed/cmd/start/cmd.go:97 +0x7ac
systemd[1]: bdjuno.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: bdjuno.service: Failed with result 'exit-code'.
systemd[1]: bdjuno.service: Consumed 3.673s CPU time.
```

## Steps to reproduce
Activate the messages module into the config.yaml file.

```
chain:
    bech32_prefix: cosmos
    modules:
       - modules
       - messages
```

## Expected behavior
BDJuno should continue processing the next blocks without crashing.

**Comment by MonikaCat** [comment]
Hey @sebastian-xlabs to fix that you need to change `bech32_prefix` inside your config.yaml file from `cosmos` to `wormhole`, like shown below: 

```
chain:
    bech32_prefix: wormhole
    modules:
        - messages
        - auth
        - bank
        - consensus
        - feegrant
        - gov
        - mint
        - modules
        - pricefeed
        - staking
        - slashing
        - distribution
        - daily refetch
        - wormhole
        - wasm
        
       ..... the rest of config file
```

**Comment by sebastian-xlabs** [comment]
Cool, it worked! Thanks!
